[package]
name = "ibmad"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
nix = { version = "0.30.1", features = ["ioctl", "memfd"] }
tracing = "0.1"
log = "0.4"
env_logger = "0.11"